# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

def self.getPropertyFromGradle(property_name)
    version_code = "0"
    begin
         file = File.new("../app/build.gradle","r")
         while (line = file.gets)
             if line.include? property_name
                versionComponents = line.strip.split(' ')
                version_code = versionComponents[versionComponents.length - 1].tr("\"","")
                break
             end
         end
         file.close
     rescue => err
         puts "An exception occured while reading gradle file: #{err}"
     end
     return version_code
end

platform :android do

    desc "Deploy a beta version to the Google Play"
    lane :beta do
      log = changelog_from_git_commits
      version_code = getPropertyFromGradle("versionCode")

      changeLogFile = File.new('./metadata/android/en-GB/changelogs/' + version_code + '.txt', 'w')
      changeLogFile.puts(log)
      changeLogFile.close

      gradle(task: "clean bundleRelease")
      upload_to_play_store(track: 'beta')
    end

    desc "Deploy a new version to the Google Play"
    lane :prod do
      gradle(task: "clean bundleRelease")
      upload_to_play_store
    end

end
